name: Build DroidSpaces Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update

        sudo apt install -y \
          git curl zip unzip bc bison flex \
          libssl-dev cpio kmod \
          build-essential libelf-dev \
          python3 gcc g++

- name: Setup ZyC Clang
      run: |
        mkdir clang
        cd clang

        wget https://github.com/ZyCromerZ/Clang/releases/download/20.0.0git-20250501-release/Clang-20.0.0git-20250501.tar.gz

        tar -xvf Clang-20.0.0git-20250501.tar.gz

        cd ..

    - name: Clone Motorola Kernel
      run: |
        git clone --depth=1 \
        -b MMI-S3RXC32.33-8-25 \
        https://github.com/MotorolaMobilityLLC/kernel-msm.git kernel

    - name: Run build script
      run: |
        chmod +x scripts/build.sh
        ./scripts/build.sh

    - name: Run AnyKernel script
      run: |
        chmod +x scripts/mkzip.sh
        ./scripts/mkzip.sh

    - name: Upload ZIP
      uses: actions/upload-artifact@v4
      with:
        name: droidspaces_kernel
        path: droidspaces_kernel.zip
